### ISSUE TITLE
Requirement 追記提案

### ISSUE THREAD

**Issue by s51517765** [swen128/twitter-text-python#2]
こちらのモジュールを利用するには、”attrs”というモジュールがインストールされている必要があるようです。
Requirementとして、”attrs”  / $pip install attrs を明示してはいかがでしょうか？

**Comment by swen128** [comment]
ご返答が遅れまして申し訳ないです。

`requirements.txt` と `setup.py` の `install_requires` に `attrs` を記述しておりますが、
仰っているのは何か別のものでしょうか？

**Comment by swen128** [comment]
いったん close しますが、問題があるようでしたら再度 open をお願いします

**Comment by s51517765** [comment]
見落としていたようです。Closeで問題ないです。
